### ISSUE TITLE
Do you have some css ?

### ISSUE THREAD

**Issue by cavo789** [jyruzicka/dugong#1]
Hello Jan-Yves,

Just in case, do you have a few examples of css for Dugong ? I've implement it in my Open Source software (https://www.marknotes.fr/docs/marknotes/Plugins/page/html/mindmap.html) and, yes, the look&feel can be better.

I fully understand that I need to code somes CSS rules but, in case of you already have great css files, can you share them ? 

Thanks a lot !

**Comment by jyruzicka** [comment]
Good to see someone making use of this! I haven't touched it for about two years.

I have some really basic CSS on the [project page](https://www.1klb.com/projects/dugong/), but nothing else I'm afraid.
